# Generated by Django 2.0.5 on 2018-07-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('menu', models.CharField(max_length=500)),
            ],
        ),
    ]
