# Generated by Django 2.0.5 on 2018-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description_first',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='description_second',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name_first',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name_second',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
